spring.application.name=cms

# Server Configuration
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/eduplus_cms
spring.data.mongodb.database=eduplus_cms

# Logging Configuration
logging.level.org.springframework.web=INFO
logging.level.com.Eduplus.cms=DEBUG
